#!/usr/bin/env python3
"""Scrape the public Emergent Mind panorama gallery into panoramas.js.

The gallery page lists ~63 curated panoramas. Each is shown as a thumbnail
whose full-resolution equirectangular image lives at the same URL with the
"_thumb" segment removed. The image host sends `Access-Control-Allow-Origin: *`,
so the browser can texture them straight onto a WebGL sphere with no proxy.

Re-run this any time to refresh the list:  python3 build.py
"""
import html
import json
import re
import sys
import urllib.request

INDEX_URL = "https://www.emergentmind.com/panoramas/"
UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36"
OUT = "panoramas.js"

# Each gallery item is an <a href="/panoramas/..."> wrapping a thumbnail <img>.
# Most link to an individual panorama (8-hex id) and carry a real alt title;
# a few are collection covers (slug id, empty alt) — for those we titleize the
# slug so nothing shows as "Untitled".
ANCHOR = re.compile(
    r'<a\b[^>]*href="/panoramas/([^"]+)"[^>]*>(.*?)</a>', re.I | re.S
)
IMG_TAG = re.compile(r"<img\b[^>]*panorama_\d+_thumb_[a-f0-9]+\.webp[^>]*>", re.I)
SRC = re.compile(r'src="([^"]+)"')
ALT = re.compile(r'alt="([^"]*)"')


def titleize_slug(slug: str) -> str:
    if re.fullmatch(r"[a-f0-9]{6,}", slug):  # opaque id, no human title
        return ""
    return slug.replace("-", " ").replace("_", " ").title()


def fetch(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read().decode("utf-8", "replace")


def main() -> int:
    page = fetch(INDEX_URL)
    seen: set[str] = set()
    panos: list[dict] = []
    for slug, block in ANCHOR.findall(page):
        tag = IMG_TAG.search(block)
        if not tag:
            continue
        m = SRC.search(tag.group(0))
        if not m:
            continue
        thumb = m.group(1)
        full = thumb.replace("_thumb", "")
        if full in seen:
            continue
        seen.add(full)
        alt = ALT.search(tag.group(0))
        title = html.unescape(alt.group(1)).strip() if alt else ""
        if not title:
            title = titleize_slug(slug)
        panos.append({"full": full, "thumb": thumb, "title": title or "Untitled"})

    if not panos:
        print("ERROR: no panoramas parsed — site markup may have changed.", file=sys.stderr)
        return 1

    body = ",\n  ".join(json.dumps(p, ensure_ascii=False) for p in panos)
    js = (
        "// Auto-generated by build.py — do not edit by hand.\n"
        f"// Source: {INDEX_URL}\n"
        f"// {len(panos)} panoramas.\n"
        f"window.PANORAMAS = [\n  {body}\n];\n"
    )
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(js)
    print(f"Wrote {OUT} with {len(panos)} panoramas.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
